"""Freeze the classifier prompt and mode list into api/_prompt.py so the live demo endpoint runs
the exact same classifier as the pipeline. Re-run after any taxonomy or prompt change."""
import importlib.util, json
spec = importlib.util.spec_from_file_location("c", "pipeline/03_classify.py"); m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
src = f'''# GENERATED by pipeline/07_build_api_prompt.py -- do not edit by hand.
MODE_IDS = {json.dumps(m.MODE_IDS)}
MODE_NAMES = {json.dumps({x["id"]: x["name"] for x in m.TAX["failure_modes"]})}
MODE_CATEGORY = {json.dumps({x["id"]: (m.TAX["categories"].get(x["category"]) if x["category"] else "Unclear") for x in m.TAX["failure_modes"]})}
SYSTEM = {json.dumps(m.build_system())}
'''
open("api/_prompt.py", "w").write(src); print("api/_prompt.py written:", len(m.build_system()), "chars,", len(m.MODE_IDS), "modes")
